import type { Preview } from '@storybook/react-vite'
import { useEffect } from 'react'
import { FabelySolarProvider } from '../src/foundations/solar-provider'
import '../src/styles/globals.css'
import './theme.css'

// globals.css pulls in Tailwind (`@import 'tailwindcss'`) and Foundations
// (`@import '../foundations/index.css'`) together, so shadcn/Tailwind-based
// components under src/components/ui render styled the same way they will
// in the app, not just Foundations' plain CSS custom properties.
//
// Fabely's real theme mechanism is the `.dark` class toggled on the document
// root (see src/styles/globals.css: `@custom-variant dark (&:is(.dark *))`).
// This decorator drives that same class from a Storybook global (flipped by
// the single-click toolbar button in .storybook/manager.tsx), instead of any
// Storybook-only theming (backgrounds addon, manager theme, etc).
const THEME_STORAGE_KEY = 'fabely-storybook-theme'
type ThemeName = 'light' | 'dark'

function getStoredTheme(): ThemeName {
  return localStorage.getItem(THEME_STORAGE_KEY) === 'dark' ? 'dark' : 'light'
}

const preview: Preview = {
  initialGlobals: {
    theme: getStoredTheme(),
  },
  decorators: [
    (Story, context) => {
      const theme: ThemeName = context.globals.theme === 'dark' ? 'dark' : 'light'

      // Applied synchronously during render, not in an effect: React fires
      // child effects before parent effects, so a child's mount-time
      // getComputedStyle() read (see ColorSwatchTable) would otherwise race
      // ahead of this and capture the pre-toggle value.
      document.documentElement.classList.toggle('dark', theme === 'dark')

      useEffect(() => {
        localStorage.setItem(THEME_STORAGE_KEY, theme)
      }, [theme])

      // Remounting on theme change re-runs every story's getComputedStyle()
      // reads (see ColorSwatchTable), so every foundation story — current and
      // future — picks up the toggle automatically with no per-story code.
      // FabelySolarProvider tags Solar SVGs so Bold Duotone secondary layers
      // use --icon-solar-secondary-opacity (~80%) from iconography.css.
      return (
        <FabelySolarProvider key={theme}>
          <Story />
        </FabelySolarProvider>
      )
    },
  ],
  parameters: {
    controls: {
      matchers: {
       color: /(background|color)$/i,
       date: /Date$/i,
      },
    },

    a11y: {
      // 'todo' - show a11y violations in the test UI only
      // 'error' - fail CI on a11y violations
      // 'off' - skip a11y checks entirely
      test: 'todo'
    },

    options: {
      // Every Foundations category follows the same conceptual reading order:
      // Raw (primitives) -> Themes (theme-dependent layers, where applicable)
      // -> Semantic (what components actually consume). Add new categories'
      // sub-pages here in that order so the sidebar keeps teaching the same
      // mental model instead of falling back to alphabetical/discovery order.
      storySort: {
        order: [
          'Design System',
          [
            'Foundations',
            [
              'Colors',
              [
                'Raw',
                'Themes',
                ['Neutrals', 'Neutrals (Migration Layer)', 'Alpha'],
                'Semantic',
                'Gradients',
                ['Primary'],
              ],
              'Spacing',
              ['Raw', 'Semantic'],
              'Radius',
              ['Raw', 'Semantic'],
              'Stroke',
              'Shadows',
              ['Base', 'Semantic'],
              'Effects',
              ['Glows', 'Focus Rings'],
              'Typography',
              [
                'Font Definitions',
                'Typography Styles',
                ['Headings', 'Paragraph', 'Manuscript', 'Captions', 'Monospaced'],
                'All Fonts',
              ],
              'Iconography',
              [
                'Overview',
                'Size Tokens',
                'Stroke & Alignment',
                'Icon Library',
                ['Lucide', 'Solar', 'Fabely Icons'],
                'Best Practices',
              ],
              'Images',
            ],
            // Primitives: wrapped vendor components (flat, alphabetical).
            // Nested families (e.g. Button) must be listed explicitly — otherwise
            // Storybook appends the folder after every leaf. Page arrays keep
            // Overview first where we have customized that order.
            'Primitives',
            [
              'Accordion',
              [
                'Overview',
                'Basic',
                'Multiple',
                'Disabled',
                'Borders',
                'Card',
                'RTL',
              ],
              'Alert',
              ['Overview', 'One Line', 'Two Lines', 'Without Icon', 'Error', 'Warning', 'Success'],
              'Alert Dialog',
              'Aspect Ratio',
              [
                'Overview',
                'Demo',
                'Square',
                'Portrait',
                'RTL',
              ],
              'Attachment',
              'Avatar',
              [
                'Overview',
                'Default',
                'With Image',
                'Fallback',
                'Several Fallback Initials',
                'Sizes',
                'Shapes',
                'Status Badge',
                'Icon Badge',
                'Group',
                'Group With Badges',
                'Group With Count',
                'Group With Count Icon',
                'Gradient',
              ],
              'Badge',
              [
                'Overview',
                'Default',
                'Variants',
                'Sizes',
                'Roundness',
                'Figma Matrix',
                'With Icon',
                'With Spinner',
                'Link',
                'Custom Colors',
                'RTL',
              ],
              'Breadcrumb',
              'Bubble',
              [
                'Overview',
                'Conversation',
                'Speakers',
                'Footer slot',
                'Destructive',
                'Group',
                'Reactions',
                'Links and Buttons',
                'Collapsible',
              ],
              'Button',
              [
                'Icon Button',
                [
                  'Overview',
                  'Default',
                  'Variants',
                  'Sizes',
                  'Shape',
                  'Matrix',
                  'Disabled',
                  'Pressed',
                ],
                'Link Button',
                [
                  'Overview',
                  'Default',
                  'Variants',
                  'Sizes',
                  'With Icon',
                  'Matrix',
                  'Disabled',
                  'Pressed',
                  'As Anchor',
                ],
                'Text Button',
                [
                  'Overview',
                  'Default',
                  'Variants',
                  'Sizes',
                  'Shape',
                  'Figma Matrix',
                  'With Icon',
                  'Spinner',
                  'Disabled',
                  'Pressed',
                  'As Link',
                  'RTL',
                ],
              ],
              'Button Group',
              [
                'Overview',
                'Spaced Toolbar',
                'Fused',
                'Orientation',
                'Sizes',
                'Shape',
                'Height Parity',
                'Spaced (nested)',
                'Separator',
                'Split',
                'Input',
                'Input Group',
                'Dropdown Menu',
                'Select',
                'Popover',
                'With Text',
                'Pagination',
                'RTL',
              ],
              'Calendar',
              [
                'Overview',
                'Basic',
                'Range',
                'Month and Year',
                'Week Numbers',
                'Booked Dates',
                'Custom Cell Size',
                'Time Zone',
                'RTL',
              ],
              'Card',
              [
                'Overview',
                'Basic',
                'Small',
                'Spacing',
                'Edge to Edge',
                'Image',
                'RTL',
              ],
              'Carousel',
              'Chart',
              [
                'Overview',
                'Basic',
                'Tooltip line',
                'No legend',
                'RTL',
              ],
              'Checkbox',
              [
                'Overview',
                'Basic',
                'Description',
                'Disabled',
                'Invalid',
                'Group',
                'Indeterminate',
                'RTL',
              ],
              'Collapsible',
              [
                'Overview',
                'Demo',
                'Basic',
                'Settings Panel',
                'File Tree',
                'RTL',
              ],
              'Combobox',
              [
                'Overview',
                'Basic',
                'Multiple',
                'Clear Button',
                'Groups',
                'Custom Items',
                'Invalid',
                'Disabled',
                'Auto Highlight',
                'Popup',
                'RTL',
              ],
              'Command',
              [
                'Overview',
                'Demo',
                'Basic',
                'Shortcuts',
                'Groups',
                'Scrollable',
                'RTL',
              ],
              'Context Menu',
              [
                'Overview',
                'Demo',
                'Basic',
                'Submenu',
                'Shortcuts',
                'Groups',
                'Icons',
                'Checkboxes',
                'Radio',
                'Destructive',
                'RTL',
              ],
              'Data Table',
              [
                'Overview',
                'Demo',
                'Basic',
                'Sorting',
                'Filtering',
                'Pagination',
                'Row Selection',
                'Column Visibility',
                'Row Actions',
                'RTL',
              ],
              'Date Picker',
              [
                'Overview',
                'Demo',
                'Basic',
                'Range Picker',
                'Date of Birth',
                'Input',
                'Time Picker',
                'Natural Language',
                'RTL',
              ],
              'Dialog',
              [
                'Overview',
                'Demo',
                'Custom Close Button',
                'No Close Button',
                'Sticky Footer',
                'Scrollable Content',
                'RTL',
              ],
              'Direction',
              ['Overview', 'Demo', 'useDirection'],
              'Drawer',
              [
                'Overview',
                'Demo',
                'Position',
                'Swipe Handle',
                'Nested',
                'Non Modal',
                'Snap Points',
                'Responsive',
                'Delivery Method',
                'RTL',
              ],
              'Dropdown Menu',
              [
                'Overview',
                'Basic',
                'Checkboxes',
                'Radio',
                'Submenu',
              ],
              'Empty',
              [
                'Overview',
                'Demo',
                'Outline',
                'Background',
                'Outline Dashed',
                'Image',
                'Avatar',
                'Avatar Group',
                'Input Group',
                'RTL',
              ],
              'Field',
              [
                'Overview',
                'Demo',
                'Input',
                'Textarea',
                'Select',
                'Input vs Select',
                'Slider',
                'Fieldset',
                'Checkbox',
                'Radio',
                'Switch',
                'Choice Card',
                'Field Group',
                'Responsive',
                'Validation',
                'RTL',
              ],
              'Hover Card',
              [
                'Overview',
                'Basic',
                'Sides',
                'RTL',
                'Surfaces',
              ],
              'Input',
              [
                'Overview',
                'Basic',
                'Field',
                'Field Group',
                'Disabled',
                'Invalid',
                'File',
                'Inline',
                'Grid',
                'Required',
                'Badge',
                'Input Group',
                'Button Group',
                'Form',
                'RTL',
                'Sizes',
                'Roundness',
                'Style',
                'Decorations',
              ],
              'Input Group',
              [
                'Overview',
                'Align',
                'Icon',
                'Text',
                'Button',
                'Kbd',
                'Dropdown',
                'Spinner',
                'Textarea',
                'RTL',
              ],
              'Input OTP',
              'Item',
              [
                'Overview',
                'Variant',
                'Size',
                'Icon',
                'Avatar',
                'Image',
                'Group',
                'Header',
                'Link',
                'Dropdown',
                'RTL',
                'Footer',
              ],
              'Kbd',
              [
                'Overview',
                'Group',
                'Button',
                'Tooltip',
                'Input Group',
                'Glow',
                'RTL',
              ],
              'Label',
              [
                'Overview',
                'Demo',
                'Error',
                'Required',
                'Field',
                'RTL',
              ],
              'ListItem',
              [
                'Overview',
                'Default',
                'Variants',
                'Sizes',
                'States',
                'With media',
                'Full composition',
              ],
              'Marker',
              'Menubar',
              'Message',
              'Message Scroller',
              'Native Select',
              'Navigation Menu',
              [
                'Overview',
                'Demo',
                'With Icon',
                'Link',
                'RTL',
              ],
              'Pagination',
              'Popover',
              'Progress',
              'Questionnaire',
              [
                'Overview',
                'Demo',
                'Multiple',
                'Freeform',
                'Skip',
                'Shortcuts',
                'Card',
                'Dialog',
              ],
              'Radio Group',
              [
                'Overview',
                'Demo',
                'Rich Radio Container',
                'Rich Radio Container Flipped',
                'Rich Icon SM',
                'Rich Icon LG',
                'Rich Block',
                'Choice Card',
                'Fieldset',
                'Disabled',
                'Invalid',
                'RTL',
              ],
              'Resizable',
              [
                'Overview',
                'Demo',
                'Vertical',
                'Handle',
                'RTL',
              ],
              'Scroll Area',
              [
                'Overview',
                'Demo',
                'Horizontal',
                'RTL',
              ],
              'Select',
              [
                'Overview',
                'Demo',
                'Groups',
                'Scrollable',
                'Disabled',
                'Invalid',
                'Align Item With Trigger',
                'RTL',
              ],
              'Separator',
              [
                'Overview',
                'Demo',
                'Vertical',
                'Menu',
                'List',
                'RTL',
              ],
              'Sheet',
              'Sidebar',
              'Skeleton',
              'Slider',
              [
                'Overview',
                'Demo',
                'Range',
                'Multiple Thumbs',
                'Vertical',
                'Controlled',
                'Disabled',
                'RTL',
              ],
              'Spinner',
              [
                'Overview',
                'Demo',
                'Size',
                'Button',
                'Badge',
                'Input Group',
                'Empty',
                'RTL',
              ],
              'Switch',
              [
                'Overview',
                'Demo',
                'Description',
                'Choice Card',
                'Disabled',
                'Invalid',
                'Size',
                'RTL',
                'Switch Light',
              ],
              'Table',
              [
                'Overview',
                'Demo',
                'Footer',
                'Actions',
                'RTL',
              ],
              'Tabs',
              [
                'Overview',
                'Demo',
                'Line',
                'Vertical',
                'Disabled',
                'Icons',
                'Size',
                'RTL',
              ],
              'Textarea',
              [
                'Overview',
                'Default',
                'Field',
                'Disabled',
                'Invalid',
                'Button',
                'Character Count',
                'Round',
                'RTL',
              ],
              'Toast',
              'Toggle',
              [
                'Overview',
                'Demo',
                'Outline',
                'With Text',
                'Size',
                'Disabled',
                'RTL',
                'Custom',
              ],
              'Toggle Group',
              [
                'Overview',
                'Demo',
                'Outline',
                'Size',
                'Spacing',
                'Round',
                'Vertical',
                'Disabled',
                'Custom',
                'RTL',
              ],
              'Tooltip',
              [
                'Overview',
                'Demo',
                'Side',
                'With Keyboard Shortcut',
                'Disabled Button',
                'RTL',
              ],
            ],
            'Atoms',
            'Molecules',
            'Organisms',
            // Feature folders alphabetical after 'Overview' (the Features
            // category's own overview page, not a folder itself) — add new
            // feature folders here in alphabetical position rather than
            // leaving them to the default fallback, so the sidebar order
            // doesn't depend on discovery/insertion order.
            'Features',
            [
              'Overview',
              'Chapter Nav Organism',
              [
                'Chapter Menu',
                'Chapter Menu List Item',
                'Add Section Inline Button',
                'Chapter Nav Button',
                'Chapter Menu Header',
              ],
              'Comments',
              'Gather',
              'Highlight',
              'Library',
              'Manuscript',
              'Promptbar',
              [
                'AI Mode Toggle',
                'Shelf',
                'Promptbar',
                [
                  'Overview',
                  'Audio Recording',
                  'Fia Speak',
                  'Gather Roam Collapsed',
                  'Gather For Scene Collapsed',
                  'Gather Roam Expanded',
                  'Gather For Scene Expanded',
                  'Scene Desk Collapsed',
                  'Fia Default Collapsed',
                  'Workflows Default Collapsed',
                  'Workflows Expanded',
                  'Workflow Related Themes',
                  'Workflow Topic Map',
                  'Workflow Develop Scene',
                ],
              ],
              'Split & Parse',
              'Theme Card',
              'Topic Map Card',
            ],
          ],
        ],
      },
    },
  },
};

export default preview;
